### ISSUE TITLE
Missing documentation about firewall UserProvide documentation

### ISSUE THREAD

**Issue by Dakhtara** [web-auth/doc#10]
Hi @Spomky  , 

I tried to implement the Symfony bundle you provided. Everything is fine. 
But I struggled with an 401 error due to the missing implementation of ObjectRepository on my UserEntityRepository. 
I watched what you did on your demo and found that you had created a specific UserProvider. 
Indeed in the documentation you specify that we should create a UserProvider, but what is not clear is that we can't use the default UserProvider of Doctrine. 

In my case I did implement the ObjectRepository on my UserEntityRepository and it works but I will switch on the UserProvider you have in the Symfony Demo. 

Maybe it could be possible to add in the documentation that we need to create our own UserProvider with an example of this UserProvider as in your Symfony demo ?

**Comment by Spomky** [comment]
OK noted.
Your are right this should be clearly explained in the doc.

**Comment by Spomky** [comment]
Hi @Dakhtara,

I’ve just created [a new section](https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way/firewall#security-bundle).
Let me know if you see something wrong or unclear.

I take the opportunity to tell you about [a JS package I created](https://github.com/web-auth/webauthn-helper). It is now implemented in the demo, but still considered as experimental (`v0.x`).
If you use it, I will be happy to get your feedback.

**Comment by Dakhtara** [comment]
@Spomky 
The new section is good for me. 

I did use some of the methods on your Js Package. Mainly these for the credentials options to transform the json Object data (like the challenge etc.). 
But for now I was looking for the implementation with Symfony, and later I will may need it for VueJS, so I will use the JS Package. 
Thanks for your work

**Comment by Spomky** [comment]
Thank you.
I close the issue now, but feel free to re-open if deemed necessary
