### ISSUE TITLE
Typo for the rp Id? maybe or maybe not:)

### ISSUE THREAD

**Issue by afridi26** [web-auth/doc#11]
He thanks for the your effort :)

I was checking out the documentation and came across the Relying Party Identifier section. Maybe be found a mistake [here](https://webauthn-doc.spomky-labs.com/pre-requisites/the-relaying-party),
<img width="589" alt="error" src="https://user-images.githubusercontent.com/5488091/83881569-2c875180-a741-11ea-9380-100ccff6b24c.PNG">

If I am not wrong and you look at the W3c specification and especially  at [Relying Party Identifier
RP ID](https://www.w3.org/TR/webauthn/#relying-party-identifier). The specification explicitly says that: 

> An RP ID is based on a host's domain name. It does not itself include a scheme or port, as an origin does.

> For example, given a Relying Party whose origin is https://login.example.com:1337, then the following RP IDs are valid: login.example.com (default) and example.com, but not m.login.example.com and not com.

for above they are missing an example for the domain who has **The Subdomain: www.**. 
For instance; https://www.exmple.com. So, in this case, setting the rpId to www.example.com is valid or not? and if you look the above case in this scenario Host or Hostname is this: www.example.com
I am not sure but the specification is quite hard to get what is right or wrong? and Maybe if I am wrong please guide me or if not please correct it.

**Comment by afridi26** [comment]
I verified it is not a typo but it was missing in the specs and www.subdomain.domain.com and www.domain.com are valid rpId.

But thanks for the documentation.

**Comment by Spomky** [comment]
The key point is that the rp Id shall be contained in the origin.

The rp ID `www.example.com` is fine and authentication/registration will work for URLs like https://www.example.com or https://m.www.example.com but not for https://example.com.

The rp ID should be determined depending on the common URLs for your web application.

If you have a web app located at https://m.my-app.com for mobiles and https://my-app.com or https://www.my-app.com, your rp ID should be `my-app.com`.

If the domain is shared between subprojects, the rp ID should be limited to that subprojects e.g. for https://(www.)site1.host.com and https://(www.)site2.host.com the rp IDs should be `site1.host.com` and `site2.host.com` respectively.

**Comment by afridi26** [comment]
Hey, @Spomky Thanks for such detail explanation with examples.
I have few questions to clarify and to make sure I get it right :)

Okay, the following comment you have made:
> The rp ID www.example.com is fine and authentication/registration will work for URLs like https://www.example.com or https://m.www.example.com but not for https://example.com

I want to talk about the above scenario.

This will create a problem if, for example, I have my domain with pre-fix www. and later I changed and removed the www (There are people I have noticed that does this for SEO purpose, a small demo you can see it [here](https://www.a2hosting.com/kb/developer-corner/apache-web-server/adding-or-removing-the-www-prefix-in-domain-urls) or some other reasons, additionally there are some security concerns about the cookies but this is a long topic with prefix and without prefix, we can discuss but imagine there is something wrong by choosing one of either value). 

So, Now, this will happen,  if I add or remove the prefix, the authentication cannot be exercised when registration is first done on www.example.com and later I as a developer change my domain URL by removing the prefix www. Now according to your comments, the RpId is changed because https://example.com and https://www.example.com are different, Similarly, if you look at Webauthn specs, the credentials are scoped to the rpId which in this case is different! As a result, it will create a problem and further authentication ceremonies will fail for all the users.

Yes, below you have a nice example to explain it fine and it really makes sense :) But what about other developers how they will get this stuff? Because when I saw your work, I thought you got this wrong and open an issue but later I Google it and look at other related documents mostly W3C which help to understand it clearly, the origin [the tuple part] and then it made sense to me.

`If you have a web app located at https://m.my-app.com for mobiles and https://my-app.com or https://www.my-app.com, your rp ID should be my-app.com.`

Yes, I was clear with below use-case.

`If the domain is shared between subprojects, the rp ID should be limited to that subprojects e.g. for https://(www.)site1.host.com and https://(www.)site2.host.com the rp IDs should be site1.host.com and site2.host.com respectively.`

But thank you, looking forward for your comments. Thank you

.

**Comment by Spomky** [comment]
> This will create a problem if, for example, I have my domain with pre-fix `www.` and later I changed and removed the `www.`

That’s correct. The credentials are linked to the rpID. This behaviour makes phishing inefficient (e.g. attacks like xn--80ak6aa92e.com that is showed as apple.com), but the caveat is that if you change your domain name (e.g. example.com to example.us), the credentials won’t work anymore.

It is not a problem if you add a prefix to your page origin. You can have one if you remove a prefix.
That’s why it is important to carefully choose the rpID. If the domain (example.com) is not shared by other projects, then it should be your rpID. This way you won’t have any trouble in the future if you have e.g. beta.example.com, m.example.com or (de|fr|en).example.com…

Another approach is to delegate the authentication process to a dedicated application with a dedicated domain.
Your application becomes a third party (trusted party). OAuth2/OpenID Connect are protocols that can manage authorization/authentication delegation in a safe way. For example, your user accounts are managed by id-provider.com and your application can be reached from example.com, example.eu or example.business. please note that this approach is much more complex to implement.

**Comment by afridi26** [comment]
Hey @Spomky Thanks for the comment. Recently I stumble upon the work of Pepe Berba 
[Link](https://pberba.github.io/security/2020/06/12/duo-u2f-phising/) regarding the DUo prompt.

The case you mentioned delegating authentication process to a dedicated application might enable MITM against your application. If I did not get this wrong because you are introducing a 3rd party service i.e. Your application becomes a third party. Can you please comment about this approach is it a good idea?? If these things happen it means WebAuthn and U2F cannot help you. Thank you

> If the integration of the U2F on the original application server, this attack will fail. If you try this with Github you will see that in a usual context, U2F is indeed not perishable. (From the post).

**Comment by Spomky** [comment]
Hi @afridi26 ,

Thank you for the link to this article. I had a very quick review and it looks well written.
It is mixing U2f and Webauthn so I will read it more carefully to understand  the whole article correctly.

The point I noted is that an attack may come from the redirection endpoint. It has always been a problem with OAuth Providers and it is known [for a long time](https://tools.ietf.org/html/rfc6819) (before 2012). Some implementations with this security issue still exist, but hopefully it is easy to solve that: all redirect endpoint should be registered and checked.

**Comment by afridi26** [comment]
Great, Thank you for the quick reply. Thanks
