### ISSUE TITLE
What To Do With $allowedCredentials?

### ISSUE THREAD

**Issue by paragonie-security** [web-auth/doc#18]
The `$allowedCredentials` in the example [here](https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-hard-way/authenticate-your-users) is defined, but never used.

([Archived copy for historical purposes](https://web.archive.org/web/20220427222347/https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-hard-way/authenticate-your-users))

**Comment by Spomky** [comment]
Hi @paragonie-security,

Many thanks for spotting this out.
I have just updated the page. This value should be used to populate the option object

```php
$publicKeyCredentialRequestOptions = 
    PublicKeyCredentialRequestOptions::create(random_bytes(32))
    ->allowCredentials(...$allowedCredentials)
;
```

Regards.
