### ISSUE TITLE
Where are the 5.0 docs?

### ISSUE THREAD

**Issue by ruudk** [web-auth/doc#30]
https://webauthn-doc.spomky-labs.com/pure-php/input-loading says 5.0 but not visible here

**Comment by Spomky** [comment]
Hi @ruudk,

Indeed, I forgot to sync the branch.
It is done now. See https://github.com/web-auth/doc/tree/v5.0

**Comment by ruudk** [comment]
Thanks!

**Comment by ruudk** [comment]
@Spomky Would it be an idea to make v5.0 the default branch too?

**Comment by Spomky** [comment]
Indeed.
I changed the default branch.
Thanks.
